import React from "react";
import WelcomeSlider from "./WelcomeSlider";

export default function Welcome() {
  return (
    <section className="welcome">
      <div className="auto__container">
        <h2>
          Welcome to
          <br />
          <span>FlyBoy</span>
        </h2>
        <div className="welcome__inner">
          <div className="welcome__inner-content">
            <p>
              FlyBoy is a collection of 5,150 unique NFTs randomly stored on the
              Ethereum blockchain. Each bear is algorithmically generated by
              combining various traits. Your FlyBoy doubles as your access to
              the FlyBoys’ Flying Club (FBFC), joining a family of NFT lovers
              who are avid travellers and aviators. The founders of FlyBoys have
              donated plots of Sandbox Land to the FlyBoy Official Vault to
              establish FBFC, the very first flying club in the metaverse world.
              FlyBoy is much more than just an avatar. Physical and Virtual
              utilities have been planned, with the first physical utility being
              a personalised aviation tag of your own, from the famous
              Aviationtag.com. The utilities and future of the FlyBoys will be a
              COLLECTIVE DECISION of all members upon voting.
            </p>
          </div>
          <WelcomeSlider />
        </div>
      </div>
    </section>
  );
}
